SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

--
-- Table structure for table `stats`
--

DROP TABLE IF EXISTS `stats`;
CREATE TABLE `stats` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `site` varchar(64) NOT NULL DEFAULT '',
  `page` varchar(255) NOT NULL DEFAULT '0',
  `ip` varchar(15) NOT NULL DEFAULT '',
  `useragent` varchar(255) NOT NULL,
  `os` varchar(16) DEFAULT NULL,
  `osversion` varchar(16) DEFAULT NULL,
  `browserbase` varchar(16) DEFAULT NULL,
  `browserversion` varchar(16) DEFAULT NULL,
  `ref` varchar(255) NOT NULL DEFAULT '',
  `ref_tld` varchar(32) DEFAULT NULL,
  `date` int(13) NOT NULL DEFAULT '0',
  `update` int(13) NOT NULL DEFAULT '0',
  `code` varchar(10) NOT NULL DEFAULT '',
  `hits` int(5) NOT NULL DEFAULT '0',
  `language` varchar(32) DEFAULT NULL,
  `country` varchar(32) DEFAULT NULL,
  `countrycode` varchar(2) DEFAULT NULL,
  `region` varchar(32) DEFAULT NULL,
  `city` varchar(32) DEFAULT NULL,
  `year` int(4) DEFAULT NULL,
  `week` int(2) DEFAULT NULL,
  `month` int(2) DEFAULT NULL,
  `day` int(2) DEFAULT NULL,
  `hour` int(2) DEFAULT NULL,
  `minute` int(2) DEFAULT NULL,
  `dayofyear` int(3) DEFAULT NULL,
  `dayofweek` int(1) DEFAULT NULL,
  `minuteofday` int(5) DEFAULT NULL,
  `bot` int(1) DEFAULT NULL,
  `mobile` int(1) DEFAULT NULL,
  `device` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ip` (`ip`),
  KEY `site` (`site`),
  KEY `year` (`year`),
  KEY `month` (`month`),
  KEY `day` (`day`),
  KEY `country` (`country`),
  KEY `language` (`language`),
  KEY `countrycode` (`countrycode`),
  KEY `hour` (`hour`),
  KEY `minute` (`minute`),
  KEY `minuteofday` (`minuteofday`),
  KEY `dayofyear` (`dayofyear`),
  KEY `bot` (`bot`),
  KEY `os` (`os`),
  KEY `osversion` (`osversion`),
  KEY `browserbase` (`browserbase`),
  KEY `browserversion` (`browserversion`),
  KEY `mobile` (`mobile`),
  KEY `region` (`region`),
  KEY `city` (`city`),
  KEY `dayofweek` (`dayofweek`),
  KEY `page` (`page`),
  KEY `device` (`device`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;
